export type ItemType =
  | 'vacanciesPopup'
  | 'tasksPopup'
  | 'itEventsPopup'
  | 'recruitersContactsPopup'
  | 'resumesPopup'
  | 'skillsPopup'
  | 'interviewsPopup'
  | 'petProjectsPopup'
  | 'aiToolsPopup'
